# Load data
```{r}
library(data.table)
```

```{r}
columns_names = read.table("UCI\ HAR\ Dataset/features.txt")

X_train = read.table("UCI\ HAR\ Dataset/train/X_train.txt", col.names = unlist(columns_names[2]))
y_train = read.table("UCI\ HAR\ Dataset/train/y_train.txt", col.names = c("Activity"))
X_test = read.table("UCI\ HAR\ Dataset/test/X_test.txt", col.names = unlist(columns_names[2]))
y_test = read.table("UCI\ HAR\ Dataset/test/y_test.txt", col.names = c("Activity"))
subjects_train = read.table("UCI\ HAR\ Dataset/train/subject_train.txt", col.names = "Subject")
subjects_test = read.table("UCI\ HAR\ Dataset/test/subject_test.txt", col.names = "Subject")
```

```{r}
head(X_train)
head(y_train)
head(X_test)
head(y_test)
table(is.na(X_train))
table(is.na(y_train))
table(is.na(X_test))
table(is.na(y_test))
```
We can see that there is not a single na value in this data set.
```{r}
# Add Subject col
X_train = dplyr::mutate(X_train, Subject = subjects_train$Subject)
X_test = dplyr::mutate(X_test, Subject = subjects_test$Subject)
```

```{r}
# Merge the X and y tables (train and test)
library(dplyr)
merged_X = dplyr::bind_rows(X_train, X_test)
table(is.na(merged_X))
merged_y = dplyr::bind_rows(y_train, y_test)
table(is.na(merged_y))
merged = dplyr::mutate(merged_X, Activity = merged_y$Activity)
```

```{r}
# Only keep mean and std cols & Activity & Subject
dt = merged[,c(unlist(grep("mean", colnames(merged))), unlist(grep("std", colnames(merged))), length(merged)-1, length(merged))]
# Change Activity numbers to factor
activity_labels = read.table("UCI\ HAR\ Dataset/activity_labels.txt")
dt$Activity = factor(dt$Activity)
levels(dt$Activity) = unlist(activity_labels[2])
```

```{r}
# Change col names
colnames(dt) = sub("fBody", "FrequencyBody", colnames(dt))
colnames(dt) = sub("tBody", "TimeBody", colnames(dt))
colnames(dt) = sub("Acc", "Acceleration", colnames(dt))
colnames(dt) = sub("Mag", "Magnitude", colnames(dt))
colnames(dt) = sub("mean", "Mean", colnames(dt))
colnames(dt) = sub("std", "Std", colnames(dt))
colnames(dt) = gsub("\\.", "", colnames(dt))
colnames(dt)
```

```{r}
average = setDT(dt)[, lapply(.SD, mean), by=c("Subject", "Activity")]
head(average)
```

